spring.application.name=saintcalendar

spring.datasource.url=jdbc:postgresql://localhost:5432/saint_calendar_db
spring.datasource.username=spring_admin
spring.datasource.password=spring_admin
spring.datasource.driver-class-name=org.postgresql.Driver
# validate
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.threads.virtual.enabled=true

spring.datasource.hikari.maximum-pool-size=20

logging.level.com.dev.saintcalendar=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# so is_martyr works without it didn´t
spring.jackson.property-naming-strategy=SNAKE_CASE